# Generated by Django 3.2.7 on 2021-09-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='NA', max_length=255)),
                ('handler', models.CharField(default='Rosita', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deal_stages', models.CharField(choices=[('prospect', 'Prospect'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed', 'Closed')], default='prospect', max_length=50)),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
            },
        ),
    ]
